# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:

- task: RunDotTEST@1
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)'
    installDir: 'C:\Program Files\Parasoft\dotTEST\2022.2'
    testConfig: 'builtin://Recommended Rules'
    publish: false
    nobuild: true
    showsettings: true
    property: |
      dtp.url=http://localhost:80
      dtp.user=admin
      dtp.password=admin
      dtp.project=Quartz .NET
      goal.ref.report.file="C:\Vault\Testing_Files\Reports\DotTest\report.xml"
      goal.ref.report.findings.exclude=true

# Uploads analysis results in the SARIF format, so that they can be accessed in the 'Scans' tab.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'report/report.sarif'
    ArtifactName: 'CodeAnalysisLogs'
    publishLocation: 'Container'

# Uploads all report files (.xml, .html, .sarif) as build artifacts.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'report'
    ArtifactName: 'DottestReports'
    publishLocation: 'Container'
    


    